hello: 							#-----Target
	echo "hello" 				#-----Command

build:
	go build -o bin/main main.go

run:
	go run main.go

compile:
	GOOS=freebsd GOARCH=386 go build -o bin/main-freebsd-386 main.go
	GOOS=linux GOARCH=386 go build -o bin/main-linux-386 main.go
	GOOS=windows GOARCH=386 go build -o bin/main-windows-386 main.go


all: compile hello